name: Deploy Tambola with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Inject .env.docker from host
        run: cp /home/super/tambola-actionrunner/.env.docker .env.docker

      - name: Stop previous containers
        run: docker-compose down || true

      - name: Build and run containers
        run: |
          docker-compose build --no-cache
          docker-compose up -d --remove-orphans
