name: Deploy via Docker Compose

on:
  push:
    branches:
      - main  # or any branch you deploy from

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Stop running containers
        run: |
          docker-compose down || true

      - name: Rebuild and run with Docker Compose
        run: |
          docker-compose pull || true
          docker-compose build --no-cache
          docker-compose up -d --remove-orphans
