name: Deploy Tambola App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bring up Docker containers
        run: docker compose up --build -d
